# https://rocket.rs/v0.5-rc/guide/configuration/

## defaults for ALL profiles
[default]
# IP address to serve on.
address = "192.168.1.39" # Local addr
# Port to serve on.
port = 0xa455
# Number of threads to use for executing futures.
workers = 8
# Keep-alive timeout seconds; disabled when 0.
keep_alive = 5 # This could become a problem if we have to read/write large files
# Max level to log. (off/normal/debug/critical)
log_level = "normal" # Isn't it the 'minimal' level instead ? like log everything above that threshold ?
# Doesn't work well with my file logger system
cli_colors = false

# Streaming read size limits.
[default.limits]
bytes = "1 B"
data-form = "1 B"
# file = "0.5 GiB" # 50 MiB
file = "1 GiB"  # 50 MiB
form = "1 B"
msgpack = "1 B"
string = "1 B"
json = "1 B"    # 50 kb data + 33% base64 + 3.5mb space for additional json data and others


# ## set only when compiled in debug mode, i.e, `cargo build`
# [debug]
# ## only the `json` key from `default` will be overridden; `form` will remain
# limits = { json = "50 MiB" }


# ## set only when compiled in release mode, i.e, `cargo build --release`
# [release]
# limits = { json = "10 MiB" }
